INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (101,'ve101ry short','mov101ie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (102,'very102 short','mo102vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (103,'very 103short','mo103vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (104,'very sh104ort','mov104ie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (105,'very sh105ort','mo105vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (106,'ve106ry short','mo106vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (107,'v107ery short','mo107vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (108,'very 108short','m108ovie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (109,'ver109y short','mov109ie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (110,'ver110y short','mo110vie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (111,'very s111hort','mov111ie');
INSERT INTO FILM (FILM_ID, DESCRIPTION, TITLE) VALUES (112,'very sho112rt','mo112vie');

INSERT INTO USER (ID, USERNAME, PASSWORD, REGISTRATIONDATE) VALUES (100, 'test', 'test', null);

INSERT INTO THEATREHALL (ID, WHICH_HALL) VALUES (101, 1);
INSERT INTO THEATREHALL (ID, WHICH_HALL) VALUES (102, 2);
